// Code generated by protoc-gen-go. DO NOT EDIT.
// source: custom.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//0.Alert
//********************************************************************************************************
type DescribeAlertsWithResourceRequest struct {
	SearchWord           string   `protobuf:"bytes,1,opt,name=search_word,json=searchWord,proto3" json:"search_word"`
	SortKey              string   `protobuf:"bytes,2,opt,name=sort_key,json=sortKey,proto3" json:"sort_key"`
	Reverse              bool     `protobuf:"varint,3,opt,name=reverse,proto3" json:"reverse"`
	Offset               uint32   `protobuf:"varint,4,opt,name=offset,proto3" json:"offset"`
	Limit                uint32   `protobuf:"varint,5,opt,name=limit,proto3" json:"limit"`
	ResourceSearch       string   `protobuf:"bytes,6,opt,name=resource_search,json=resourceSearch,proto3" json:"resource_search"`
	AlertId              []string `protobuf:"bytes,7,rep,name=alert_id,json=alertId,proto3" json:"alert_id"`
	AlertName            []string `protobuf:"bytes,8,rep,name=alert_name,json=alertName,proto3" json:"alert_name"`
	Disabled             []bool   `protobuf:"varint,9,rep,packed,name=disabled,proto3" json:"disabled"`
	RunningStatus        []string `protobuf:"bytes,10,rep,name=running_status,json=runningStatus,proto3" json:"running_status"`
	PolicyId             []string `protobuf:"bytes,11,rep,name=policy_id,json=policyId,proto3" json:"policy_id"`
	RsFilterId           []string `protobuf:"bytes,12,rep,name=rs_filter_id,json=rsFilterId,proto3" json:"rs_filter_id"`
	ExecutorId           []string `protobuf:"bytes,13,rep,name=executor_id,json=executorId,proto3" json:"executor_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeAlertsWithResourceRequest) Reset()         { *m = DescribeAlertsWithResourceRequest{} }
func (m *DescribeAlertsWithResourceRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeAlertsWithResourceRequest) ProtoMessage()    {}
func (*DescribeAlertsWithResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0669528d4dffbbe2, []int{0}
}

func (m *DescribeAlertsWithResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeAlertsWithResourceRequest.Unmarshal(m, b)
}
func (m *DescribeAlertsWithResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeAlertsWithResourceRequest.Marshal(b, m, deterministic)
}
func (m *DescribeAlertsWithResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeAlertsWithResourceRequest.Merge(m, src)
}
func (m *DescribeAlertsWithResourceRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeAlertsWithResourceRequest.Size(m)
}
func (m *DescribeAlertsWithResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeAlertsWithResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeAlertsWithResourceRequest proto.InternalMessageInfo

func (m *DescribeAlertsWithResourceRequest) GetSearchWord() string {
	if m != nil {
		return m.SearchWord
	}
	return ""
}

func (m *DescribeAlertsWithResourceRequest) GetSortKey() string {
	if m != nil {
		return m.SortKey
	}
	return ""
}

func (m *DescribeAlertsWithResourceRequest) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

func (m *DescribeAlertsWithResourceRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DescribeAlertsWithResourceRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DescribeAlertsWithResourceRequest) GetResourceSearch() string {
	if m != nil {
		return m.ResourceSearch
	}
	return ""
}

func (m *DescribeAlertsWithResourceRequest) GetAlertId() []string {
	if m != nil {
		return m.AlertId
	}
	return nil
}

func (m *DescribeAlertsWithResourceRequest) GetAlertName() []string {
	if m != nil {
		return m.AlertName
	}
	return nil
}

func (m *DescribeAlertsWithResourceRequest) GetDisabled() []bool {
	if m != nil {
		return m.Disabled
	}
	return nil
}

func (m *DescribeAlertsWithResourceRequest) GetRunningStatus() []string {
	if m != nil {
		return m.RunningStatus
	}
	return nil
}

func (m *DescribeAlertsWithResourceRequest) GetPolicyId() []string {
	if m != nil {
		return m.PolicyId
	}
	return nil
}

func (m *DescribeAlertsWithResourceRequest) GetRsFilterId() []string {
	if m != nil {
		return m.RsFilterId
	}
	return nil
}

func (m *DescribeAlertsWithResourceRequest) GetExecutorId() []string {
	if m != nil {
		return m.ExecutorId
	}
	return nil
}

type DescribeAlertsWithResourceResponse struct {
	Total                uint32   `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	AlertSet             []*Alert `protobuf:"bytes,2,rep,name=alert_set,json=alertSet,proto3" json:"alert_set"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeAlertsWithResourceResponse) Reset()         { *m = DescribeAlertsWithResourceResponse{} }
func (m *DescribeAlertsWithResourceResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeAlertsWithResourceResponse) ProtoMessage()    {}
func (*DescribeAlertsWithResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0669528d4dffbbe2, []int{1}
}

func (m *DescribeAlertsWithResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeAlertsWithResourceResponse.Unmarshal(m, b)
}
func (m *DescribeAlertsWithResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeAlertsWithResourceResponse.Marshal(b, m, deterministic)
}
func (m *DescribeAlertsWithResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeAlertsWithResourceResponse.Merge(m, src)
}
func (m *DescribeAlertsWithResourceResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeAlertsWithResourceResponse.Size(m)
}
func (m *DescribeAlertsWithResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeAlertsWithResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeAlertsWithResourceResponse proto.InternalMessageInfo

func (m *DescribeAlertsWithResourceResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *DescribeAlertsWithResourceResponse) GetAlertSet() []*Alert {
	if m != nil {
		return m.AlertSet
	}
	return nil
}

type AlertDetail struct {
	AlertId              string               `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id"`
	AlertName            string               `protobuf:"bytes,2,opt,name=alert_name,json=alertName,proto3" json:"alert_name"`
	Disabled             bool                 `protobuf:"varint,3,opt,name=disabled,proto3" json:"disabled"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time"`
	RunningStatus        string               `protobuf:"bytes,5,opt,name=running_status,json=runningStatus,proto3" json:"running_status"`
	AlertStatus          string               `protobuf:"bytes,6,opt,name=alert_status,json=alertStatus,proto3" json:"alert_status"`
	PolicyId             string               `protobuf:"bytes,7,opt,name=policy_id,json=policyId,proto3" json:"policy_id"`
	RsFilterName         string               `protobuf:"bytes,8,opt,name=rs_filter_name,json=rsFilterName,proto3" json:"rs_filter_name"`
	RsFilterParam        string               `protobuf:"bytes,9,opt,name=rs_filter_param,json=rsFilterParam,proto3" json:"rs_filter_param"`
	RsTypeName           string               `protobuf:"bytes,10,opt,name=rs_type_name,json=rsTypeName,proto3" json:"rs_type_name"`
	ExecutorId           string               `protobuf:"bytes,11,opt,name=executor_id,json=executorId,proto3" json:"executor_id"`
	PolicyName           string               `protobuf:"bytes,12,opt,name=policy_name,json=policyName,proto3" json:"policy_name"`
	PolicyDescription    string               `protobuf:"bytes,13,opt,name=policy_description,json=policyDescription,proto3" json:"policy_description"`
	PolicyConfig         string               `protobuf:"bytes,14,opt,name=policy_config,json=policyConfig,proto3" json:"policy_config"`
	Creator              string               `protobuf:"bytes,15,opt,name=creator,proto3" json:"creator"`
	AvailableStartTime   string               `protobuf:"bytes,16,opt,name=available_start_time,json=availableStartTime,proto3" json:"available_start_time"`
	AvailableEndTime     string               `protobuf:"bytes,17,opt,name=available_end_time,json=availableEndTime,proto3" json:"available_end_time"`
	Language             string               `protobuf:"bytes,18,opt,name=language,proto3" json:"language"`
	Metrics              []string             `protobuf:"bytes,19,rep,name=metrics,proto3" json:"metrics"`
	RulesCount           uint32               `protobuf:"varint,20,opt,name=rules_count,json=rulesCount,proto3" json:"rules_count"`
	PositivesCount       uint32               `protobuf:"varint,21,opt,name=positives_count,json=positivesCount,proto3" json:"positives_count"`
	MostRecentAlertTime  string               `protobuf:"bytes,22,opt,name=most_recent_alert_time,json=mostRecentAlertTime,proto3" json:"most_recent_alert_time"`
	NfAddressListId      string               `protobuf:"bytes,23,opt,name=nf_address_list_id,json=nfAddressListId,proto3" json:"nf_address_list_id"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AlertDetail) Reset()         { *m = AlertDetail{} }
func (m *AlertDetail) String() string { return proto.CompactTextString(m) }
func (*AlertDetail) ProtoMessage()    {}
func (*AlertDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_0669528d4dffbbe2, []int{2}
}

func (m *AlertDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertDetail.Unmarshal(m, b)
}
func (m *AlertDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertDetail.Marshal(b, m, deterministic)
}
func (m *AlertDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertDetail.Merge(m, src)
}
func (m *AlertDetail) XXX_Size() int {
	return xxx_messageInfo_AlertDetail.Size(m)
}
func (m *AlertDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertDetail.DiscardUnknown(m)
}

var xxx_messageInfo_AlertDetail proto.InternalMessageInfo

func (m *AlertDetail) GetAlertId() string {
	if m != nil {
		return m.AlertId
	}
	return ""
}

func (m *AlertDetail) GetAlertName() string {
	if m != nil {
		return m.AlertName
	}
	return ""
}

func (m *AlertDetail) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *AlertDetail) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *AlertDetail) GetRunningStatus() string {
	if m != nil {
		return m.RunningStatus
	}
	return ""
}

func (m *AlertDetail) GetAlertStatus() string {
	if m != nil {
		return m.AlertStatus
	}
	return ""
}

func (m *AlertDetail) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

func (m *AlertDetail) GetRsFilterName() string {
	if m != nil {
		return m.RsFilterName
	}
	return ""
}

func (m *AlertDetail) GetRsFilterParam() string {
	if m != nil {
		return m.RsFilterParam
	}
	return ""
}

func (m *AlertDetail) GetRsTypeName() string {
	if m != nil {
		return m.RsTypeName
	}
	return ""
}

func (m *AlertDetail) GetExecutorId() string {
	if m != nil {
		return m.ExecutorId
	}
	return ""
}

func (m *AlertDetail) GetPolicyName() string {
	if m != nil {
		return m.PolicyName
	}
	return ""
}

func (m *AlertDetail) GetPolicyDescription() string {
	if m != nil {
		return m.PolicyDescription
	}
	return ""
}

func (m *AlertDetail) GetPolicyConfig() string {
	if m != nil {
		return m.PolicyConfig
	}
	return ""
}

func (m *AlertDetail) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *AlertDetail) GetAvailableStartTime() string {
	if m != nil {
		return m.AvailableStartTime
	}
	return ""
}

func (m *AlertDetail) GetAvailableEndTime() string {
	if m != nil {
		return m.AvailableEndTime
	}
	return ""
}

func (m *AlertDetail) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *AlertDetail) GetMetrics() []string {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *AlertDetail) GetRulesCount() uint32 {
	if m != nil {
		return m.RulesCount
	}
	return 0
}

func (m *AlertDetail) GetPositivesCount() uint32 {
	if m != nil {
		return m.PositivesCount
	}
	return 0
}

func (m *AlertDetail) GetMostRecentAlertTime() string {
	if m != nil {
		return m.MostRecentAlertTime
	}
	return ""
}

func (m *AlertDetail) GetNfAddressListId() string {
	if m != nil {
		return m.NfAddressListId
	}
	return ""
}

type DescribeAlertDetailsRequest struct {
	SearchWord           string   `protobuf:"bytes,1,opt,name=search_word,json=searchWord,proto3" json:"search_word"`
	SortKey              string   `protobuf:"bytes,2,opt,name=sort_key,json=sortKey,proto3" json:"sort_key"`
	Reverse              bool     `protobuf:"varint,3,opt,name=reverse,proto3" json:"reverse"`
	Offset               uint32   `protobuf:"varint,4,opt,name=offset,proto3" json:"offset"`
	Limit                uint32   `protobuf:"varint,5,opt,name=limit,proto3" json:"limit"`
	ResourceSearch       string   `protobuf:"bytes,6,opt,name=resource_search,json=resourceSearch,proto3" json:"resource_search"`
	AlertId              []string `protobuf:"bytes,7,rep,name=alert_id,json=alertId,proto3" json:"alert_id"`
	AlertName            []string `protobuf:"bytes,8,rep,name=alert_name,json=alertName,proto3" json:"alert_name"`
	Disabled             []bool   `protobuf:"varint,9,rep,packed,name=disabled,proto3" json:"disabled"`
	RunningStatus        []string `protobuf:"bytes,10,rep,name=running_status,json=runningStatus,proto3" json:"running_status"`
	PolicyId             []string `protobuf:"bytes,11,rep,name=policy_id,json=policyId,proto3" json:"policy_id"`
	Creator              []string `protobuf:"bytes,12,rep,name=creator,proto3" json:"creator"`
	RsFilterId           []string `protobuf:"bytes,13,rep,name=rs_filter_id,json=rsFilterId,proto3" json:"rs_filter_id"`
	ExecutorId           []string `protobuf:"bytes,14,rep,name=executor_id,json=executorId,proto3" json:"executor_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeAlertDetailsRequest) Reset()         { *m = DescribeAlertDetailsRequest{} }
func (m *DescribeAlertDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeAlertDetailsRequest) ProtoMessage()    {}
func (*DescribeAlertDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0669528d4dffbbe2, []int{3}
}

func (m *DescribeAlertDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeAlertDetailsRequest.Unmarshal(m, b)
}
func (m *DescribeAlertDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeAlertDetailsRequest.Marshal(b, m, deterministic)
}
func (m *DescribeAlertDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeAlertDetailsRequest.Merge(m, src)
}
func (m *DescribeAlertDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeAlertDetailsRequest.Size(m)
}
func (m *DescribeAlertDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeAlertDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeAlertDetailsRequest proto.InternalMessageInfo

func (m *DescribeAlertDetailsRequest) GetSearchWord() string {
	if m != nil {
		return m.SearchWord
	}
	return ""
}

func (m *DescribeAlertDetailsRequest) GetSortKey() string {
	if m != nil {
		return m.SortKey
	}
	return ""
}

func (m *DescribeAlertDetailsRequest) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

func (m *DescribeAlertDetailsRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DescribeAlertDetailsRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DescribeAlertDetailsRequest) GetResourceSearch() string {
	if m != nil {
		return m.ResourceSearch
	}
	return ""
}

func (m *DescribeAlertDetailsRequest) GetAlertId() []string {
	if m != nil {
		return m.AlertId
	}
	return nil
}

func (m *DescribeAlertDetailsRequest) GetAlertName() []string {
	if m != nil {
		return m.AlertName
	}
	return nil
}

func (m *DescribeAlertDetailsRequest) GetDisabled() []bool {
	if m != nil {
		return m.Disabled
	}
	return nil
}

func (m *DescribeAlertDetailsRequest) GetRunningStatus() []string {
	if m != nil {
		return m.RunningStatus
	}
	return nil
}

func (m *DescribeAlertDetailsRequest) GetPolicyId() []string {
	if m != nil {
		return m.PolicyId
	}
	return nil
}

func (m *DescribeAlertDetailsRequest) GetCreator() []string {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *DescribeAlertDetailsRequest) GetRsFilterId() []string {
	if m != nil {
		return m.RsFilterId
	}
	return nil
}

func (m *DescribeAlertDetailsRequest) GetExecutorId() []string {
	if m != nil {
		return m.ExecutorId
	}
	return nil
}

type DescribeAlertDetailsResponse struct {
	Total                uint32         `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	AlertdetailSet       []*AlertDetail `protobuf:"bytes,2,rep,name=alertdetail_set,json=alertdetailSet,proto3" json:"alertdetail_set"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DescribeAlertDetailsResponse) Reset()         { *m = DescribeAlertDetailsResponse{} }
func (m *DescribeAlertDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeAlertDetailsResponse) ProtoMessage()    {}
func (*DescribeAlertDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0669528d4dffbbe2, []int{4}
}

func (m *DescribeAlertDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeAlertDetailsResponse.Unmarshal(m, b)
}
func (m *DescribeAlertDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeAlertDetailsResponse.Marshal(b, m, deterministic)
}
func (m *DescribeAlertDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeAlertDetailsResponse.Merge(m, src)
}
func (m *DescribeAlertDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeAlertDetailsResponse.Size(m)
}
func (m *DescribeAlertDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeAlertDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeAlertDetailsResponse proto.InternalMessageInfo

func (m *DescribeAlertDetailsResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *DescribeAlertDetailsResponse) GetAlertdetailSet() []*AlertDetail {
	if m != nil {
		return m.AlertdetailSet
	}
	return nil
}

type ResourceStatus struct {
	ResourceName         string   `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name"`
	CurrentLevel         string   `protobuf:"bytes,2,opt,name=current_level,json=currentLevel,proto3" json:"current_level"`
	PositiveCount        uint32   `protobuf:"varint,3,opt,name=positive_count,json=positiveCount,proto3" json:"positive_count"`
	CumulatedSendCount   uint32   `protobuf:"varint,4,opt,name=cumulated_send_count,json=cumulatedSendCount,proto3" json:"cumulated_send_count"`
	NextResendInterval   uint32   `protobuf:"varint,5,opt,name=next_resend_interval,json=nextResendInterval,proto3" json:"next_resend_interval"`
	NextSendableTime     string   `protobuf:"bytes,6,opt,name=next_sendable_time,json=nextSendableTime,proto3" json:"next_sendable_time"`
	AggregatedAlerts     string   `protobuf:"bytes,7,opt,name=aggregated_alerts,json=aggregatedAlerts,proto3" json:"aggregated_alerts"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceStatus) Reset()         { *m = ResourceStatus{} }
func (m *ResourceStatus) String() string { return proto.CompactTextString(m) }
func (*ResourceStatus) ProtoMessage()    {}
func (*ResourceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_0669528d4dffbbe2, []int{5}
}

func (m *ResourceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceStatus.Unmarshal(m, b)
}
func (m *ResourceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceStatus.Marshal(b, m, deterministic)
}
func (m *ResourceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceStatus.Merge(m, src)
}
func (m *ResourceStatus) XXX_Size() int {
	return xxx_messageInfo_ResourceStatus.Size(m)
}
func (m *ResourceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceStatus proto.InternalMessageInfo

func (m *ResourceStatus) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *ResourceStatus) GetCurrentLevel() string {
	if m != nil {
		return m.CurrentLevel
	}
	return ""
}

func (m *ResourceStatus) GetPositiveCount() uint32 {
	if m != nil {
		return m.PositiveCount
	}
	return 0
}

func (m *ResourceStatus) GetCumulatedSendCount() uint32 {
	if m != nil {
		return m.CumulatedSendCount
	}
	return 0
}

func (m *ResourceStatus) GetNextResendInterval() uint32 {
	if m != nil {
		return m.NextResendInterval
	}
	return 0
}

func (m *ResourceStatus) GetNextSendableTime() string {
	if m != nil {
		return m.NextSendableTime
	}
	return ""
}

func (m *ResourceStatus) GetAggregatedAlerts() string {
	if m != nil {
		return m.AggregatedAlerts
	}
	return ""
}

type AlertStatus struct {
	RuleId               string               `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id"`
	RuleName             string               `protobuf:"bytes,2,opt,name=rule_name,json=ruleName,proto3" json:"rule_name"`
	Disabled             bool                 `protobuf:"varint,3,opt,name=disabled,proto3" json:"disabled"`
	MonitorPeriods       uint32               `protobuf:"varint,4,opt,name=monitor_periods,json=monitorPeriods,proto3" json:"monitor_periods"`
	Severity             string               `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity"`
	MetricsType          string               `protobuf:"bytes,6,opt,name=metrics_type,json=metricsType,proto3" json:"metrics_type"`
	ConditionType        string               `protobuf:"bytes,7,opt,name=condition_type,json=conditionType,proto3" json:"condition_type"`
	Thresholds           string               `protobuf:"bytes,8,opt,name=thresholds,proto3" json:"thresholds"`
	Unit                 string               `protobuf:"bytes,9,opt,name=unit,proto3" json:"unit"`
	ConsecutiveCount     uint32               `protobuf:"varint,10,opt,name=consecutive_count,json=consecutiveCount,proto3" json:"consecutive_count"`
	Inhibit              bool                 `protobuf:"varint,11,opt,name=inhibit,proto3" json:"inhibit"`
	MetricName           string               `protobuf:"bytes,12,opt,name=metric_name,json=metricName,proto3" json:"metric_name"`
	Resources            []*ResourceStatus    `protobuf:"bytes,13,rep,name=resources,proto3" json:"resources"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,14,opt,name=create_time,json=createTime,proto3" json:"create_time"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,15,opt,name=update_time,json=updateTime,proto3" json:"update_time"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AlertStatus) Reset()         { *m = AlertStatus{} }
func (m *AlertStatus) String() string { return proto.CompactTextString(m) }
func (*AlertStatus) ProtoMessage()    {}
func (*AlertStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_0669528d4dffbbe2, []int{6}
}

func (m *AlertStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertStatus.Unmarshal(m, b)
}
func (m *AlertStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertStatus.Marshal(b, m, deterministic)
}
func (m *AlertStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertStatus.Merge(m, src)
}
func (m *AlertStatus) XXX_Size() int {
	return xxx_messageInfo_AlertStatus.Size(m)
}
func (m *AlertStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertStatus.DiscardUnknown(m)
}

var xxx_messageInfo_AlertStatus proto.InternalMessageInfo

func (m *AlertStatus) GetRuleId() string {
	if m != nil {
		return m.RuleId
	}
	return ""
}

func (m *AlertStatus) GetRuleName() string {
	if m != nil {
		return m.RuleName
	}
	return ""
}

func (m *AlertStatus) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *AlertStatus) GetMonitorPeriods() uint32 {
	if m != nil {
		return m.MonitorPeriods
	}
	return 0
}

func (m *AlertStatus) GetSeverity() string {
	if m != nil {
		return m.Severity
	}
	return ""
}

func (m *AlertStatus) GetMetricsType() string {
	if m != nil {
		return m.MetricsType
	}
	return ""
}

func (m *AlertStatus) GetConditionType() string {
	if m != nil {
		return m.ConditionType
	}
	return ""
}

func (m *AlertStatus) GetThresholds() string {
	if m != nil {
		return m.Thresholds
	}
	return ""
}

func (m *AlertStatus) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *AlertStatus) GetConsecutiveCount() uint32 {
	if m != nil {
		return m.ConsecutiveCount
	}
	return 0
}

func (m *AlertStatus) GetInhibit() bool {
	if m != nil {
		return m.Inhibit
	}
	return false
}

func (m *AlertStatus) GetMetricName() string {
	if m != nil {
		return m.MetricName
	}
	return ""
}

func (m *AlertStatus) GetResources() []*ResourceStatus {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *AlertStatus) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *AlertStatus) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type DescribeAlertStatusRequest struct {
	SearchWord           string   `protobuf:"bytes,1,opt,name=search_word,json=searchWord,proto3" json:"search_word"`
	SortKey              string   `protobuf:"bytes,2,opt,name=sort_key,json=sortKey,proto3" json:"sort_key"`
	Reverse              bool     `protobuf:"varint,3,opt,name=reverse,proto3" json:"reverse"`
	Offset               uint32   `protobuf:"varint,4,opt,name=offset,proto3" json:"offset"`
	Limit                uint32   `protobuf:"varint,5,opt,name=limit,proto3" json:"limit"`
	ResourceSearch       string   `protobuf:"bytes,6,opt,name=resource_search,json=resourceSearch,proto3" json:"resource_search"`
	AlertId              []string `protobuf:"bytes,7,rep,name=alert_id,json=alertId,proto3" json:"alert_id"`
	AlertName            []string `protobuf:"bytes,8,rep,name=alert_name,json=alertName,proto3" json:"alert_name"`
	Disabled             []bool   `protobuf:"varint,9,rep,packed,name=disabled,proto3" json:"disabled"`
	RunningStatus        []string `protobuf:"bytes,10,rep,name=running_status,json=runningStatus,proto3" json:"running_status"`
	PolicyId             []string `protobuf:"bytes,11,rep,name=policy_id,json=policyId,proto3" json:"policy_id"`
	Creator              []string `protobuf:"bytes,12,rep,name=creator,proto3" json:"creator"`
	RsFilterId           []string `protobuf:"bytes,13,rep,name=rs_filter_id,json=rsFilterId,proto3" json:"rs_filter_id"`
	ExecutorId           []string `protobuf:"bytes,14,rep,name=executor_id,json=executorId,proto3" json:"executor_id"`
	RuleId               []string `protobuf:"bytes,15,rep,name=rule_id,json=ruleId,proto3" json:"rule_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeAlertStatusRequest) Reset()         { *m = DescribeAlertStatusRequest{} }
func (m *DescribeAlertStatusRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeAlertStatusRequest) ProtoMessage()    {}
func (*DescribeAlertStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0669528d4dffbbe2, []int{7}
}

func (m *DescribeAlertStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeAlertStatusRequest.Unmarshal(m, b)
}
func (m *DescribeAlertStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeAlertStatusRequest.Marshal(b, m, deterministic)
}
func (m *DescribeAlertStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeAlertStatusRequest.Merge(m, src)
}
func (m *DescribeAlertStatusRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeAlertStatusRequest.Size(m)
}
func (m *DescribeAlertStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeAlertStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeAlertStatusRequest proto.InternalMessageInfo

func (m *DescribeAlertStatusRequest) GetSearchWord() string {
	if m != nil {
		return m.SearchWord
	}
	return ""
}

func (m *DescribeAlertStatusRequest) GetSortKey() string {
	if m != nil {
		return m.SortKey
	}
	return ""
}

func (m *DescribeAlertStatusRequest) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

func (m *DescribeAlertStatusRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DescribeAlertStatusRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DescribeAlertStatusRequest) GetResourceSearch() string {
	if m != nil {
		return m.ResourceSearch
	}
	return ""
}

func (m *DescribeAlertStatusRequest) GetAlertId() []string {
	if m != nil {
		return m.AlertId
	}
	return nil
}

func (m *DescribeAlertStatusRequest) GetAlertName() []string {
	if m != nil {
		return m.AlertName
	}
	return nil
}

func (m *DescribeAlertStatusRequest) GetDisabled() []bool {
	if m != nil {
		return m.Disabled
	}
	return nil
}

func (m *DescribeAlertStatusRequest) GetRunningStatus() []string {
	if m != nil {
		return m.RunningStatus
	}
	return nil
}

func (m *DescribeAlertStatusRequest) GetPolicyId() []string {
	if m != nil {
		return m.PolicyId
	}
	return nil
}

func (m *DescribeAlertStatusRequest) GetCreator() []string {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *DescribeAlertStatusRequest) GetRsFilterId() []string {
	if m != nil {
		return m.RsFilterId
	}
	return nil
}

func (m *DescribeAlertStatusRequest) GetExecutorId() []string {
	if m != nil {
		return m.ExecutorId
	}
	return nil
}

func (m *DescribeAlertStatusRequest) GetRuleId() []string {
	if m != nil {
		return m.RuleId
	}
	return nil
}

type DescribeAlertStatusResponse struct {
	Total                uint32         `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	AlertstatusSet       []*AlertStatus `protobuf:"bytes,2,rep,name=alertstatus_set,json=alertstatusSet,proto3" json:"alertstatus_set"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DescribeAlertStatusResponse) Reset()         { *m = DescribeAlertStatusResponse{} }
func (m *DescribeAlertStatusResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeAlertStatusResponse) ProtoMessage()    {}
func (*DescribeAlertStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0669528d4dffbbe2, []int{8}
}

func (m *DescribeAlertStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeAlertStatusResponse.Unmarshal(m, b)
}
func (m *DescribeAlertStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeAlertStatusResponse.Marshal(b, m, deterministic)
}
func (m *DescribeAlertStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeAlertStatusResponse.Merge(m, src)
}
func (m *DescribeAlertStatusResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeAlertStatusResponse.Size(m)
}
func (m *DescribeAlertStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeAlertStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeAlertStatusResponse proto.InternalMessageInfo

func (m *DescribeAlertStatusResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *DescribeAlertStatusResponse) GetAlertstatusSet() []*AlertStatus {
	if m != nil {
		return m.AlertstatusSet
	}
	return nil
}

//1.History
//********************************************************************************************************
type HistoryDetail struct {
	HistoryId            string               `protobuf:"bytes,1,opt,name=history_id,json=historyId,proto3" json:"history_id"`
	HistoryName          string               `protobuf:"bytes,2,opt,name=history_name,json=historyName,proto3" json:"history_name"`
	RuleId               string               `protobuf:"bytes,3,opt,name=rule_id,json=ruleId,proto3" json:"rule_id"`
	RuleName             string               `protobuf:"bytes,4,opt,name=rule_name,json=ruleName,proto3" json:"rule_name"`
	Event                string               `protobuf:"bytes,5,opt,name=event,proto3" json:"event"`
	NotificationId       string               `protobuf:"bytes,6,opt,name=notification_id,json=notificationId,proto3" json:"notification_id"`
	NotificationStatus   string               `protobuf:"bytes,7,opt,name=notification_status,json=notificationStatus,proto3" json:"notification_status"`
	Severity             string               `protobuf:"bytes,8,opt,name=severity,proto3" json:"severity"`
	RsTypeName           string               `protobuf:"bytes,9,opt,name=rs_type_name,json=rsTypeName,proto3" json:"rs_type_name"`
	RsFilterName         string               `protobuf:"bytes,10,opt,name=rs_filter_name,json=rsFilterName,proto3" json:"rs_filter_name"`
	MetricName           string               `protobuf:"bytes,11,opt,name=metric_name,json=metricName,proto3" json:"metric_name"`
	ConditionType        string               `protobuf:"bytes,12,opt,name=condition_type,json=conditionType,proto3" json:"condition_type"`
	Thresholds           string               `protobuf:"bytes,13,opt,name=thresholds,proto3" json:"thresholds"`
	Unit                 string               `protobuf:"bytes,14,opt,name=unit,proto3" json:"unit"`
	AlertName            string               `protobuf:"bytes,15,opt,name=alert_name,json=alertName,proto3" json:"alert_name"`
	RsFilterParam        string               `protobuf:"bytes,16,opt,name=rs_filter_param,json=rsFilterParam,proto3" json:"rs_filter_param"`
	ResourceName         string               `protobuf:"bytes,17,opt,name=resource_name,json=resourceName,proto3" json:"resource_name"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,18,opt,name=create_time,json=createTime,proto3" json:"create_time"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,19,opt,name=update_time,json=updateTime,proto3" json:"update_time"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HistoryDetail) Reset()         { *m = HistoryDetail{} }
func (m *HistoryDetail) String() string { return proto.CompactTextString(m) }
func (*HistoryDetail) ProtoMessage()    {}
func (*HistoryDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_0669528d4dffbbe2, []int{9}
}

func (m *HistoryDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryDetail.Unmarshal(m, b)
}
func (m *HistoryDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryDetail.Marshal(b, m, deterministic)
}
func (m *HistoryDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryDetail.Merge(m, src)
}
func (m *HistoryDetail) XXX_Size() int {
	return xxx_messageInfo_HistoryDetail.Size(m)
}
func (m *HistoryDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryDetail.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryDetail proto.InternalMessageInfo

func (m *HistoryDetail) GetHistoryId() string {
	if m != nil {
		return m.HistoryId
	}
	return ""
}

func (m *HistoryDetail) GetHistoryName() string {
	if m != nil {
		return m.HistoryName
	}
	return ""
}

func (m *HistoryDetail) GetRuleId() string {
	if m != nil {
		return m.RuleId
	}
	return ""
}

func (m *HistoryDetail) GetRuleName() string {
	if m != nil {
		return m.RuleName
	}
	return ""
}

func (m *HistoryDetail) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *HistoryDetail) GetNotificationId() string {
	if m != nil {
		return m.NotificationId
	}
	return ""
}

func (m *HistoryDetail) GetNotificationStatus() string {
	if m != nil {
		return m.NotificationStatus
	}
	return ""
}

func (m *HistoryDetail) GetSeverity() string {
	if m != nil {
		return m.Severity
	}
	return ""
}

func (m *HistoryDetail) GetRsTypeName() string {
	if m != nil {
		return m.RsTypeName
	}
	return ""
}

func (m *HistoryDetail) GetRsFilterName() string {
	if m != nil {
		return m.RsFilterName
	}
	return ""
}

func (m *HistoryDetail) GetMetricName() string {
	if m != nil {
		return m.MetricName
	}
	return ""
}

func (m *HistoryDetail) GetConditionType() string {
	if m != nil {
		return m.ConditionType
	}
	return ""
}

func (m *HistoryDetail) GetThresholds() string {
	if m != nil {
		return m.Thresholds
	}
	return ""
}

func (m *HistoryDetail) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *HistoryDetail) GetAlertName() string {
	if m != nil {
		return m.AlertName
	}
	return ""
}

func (m *HistoryDetail) GetRsFilterParam() string {
	if m != nil {
		return m.RsFilterParam
	}
	return ""
}

func (m *HistoryDetail) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *HistoryDetail) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *HistoryDetail) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type DescribeHistoryDetailRequest struct {
	SearchWord           string   `protobuf:"bytes,1,opt,name=search_word,json=searchWord,proto3" json:"search_word"`
	SortKey              string   `protobuf:"bytes,2,opt,name=sort_key,json=sortKey,proto3" json:"sort_key"`
	Reverse              bool     `protobuf:"varint,3,opt,name=reverse,proto3" json:"reverse"`
	Offset               uint32   `protobuf:"varint,4,opt,name=offset,proto3" json:"offset"`
	Limit                uint32   `protobuf:"varint,5,opt,name=limit,proto3" json:"limit"`
	ResourceSearch       string   `protobuf:"bytes,6,opt,name=resource_search,json=resourceSearch,proto3" json:"resource_search"`
	HistoryId            []string `protobuf:"bytes,7,rep,name=history_id,json=historyId,proto3" json:"history_id"`
	HistoryName          []string `protobuf:"bytes,8,rep,name=history_name,json=historyName,proto3" json:"history_name"`
	AlertName            []string `protobuf:"bytes,9,rep,name=alert_name,json=alertName,proto3" json:"alert_name"`
	RuleName             []string `protobuf:"bytes,10,rep,name=rule_name,json=ruleName,proto3" json:"rule_name"`
	Event                []string `protobuf:"bytes,11,rep,name=event,proto3" json:"event"`
	RuleId               []string `protobuf:"bytes,12,rep,name=rule_id,json=ruleId,proto3" json:"rule_id"`
	ResourceName         []string `protobuf:"bytes,13,rep,name=resource_name,json=resourceName,proto3" json:"resource_name"`
	Recent               bool     `protobuf:"varint,14,opt,name=recent,proto3" json:"recent"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeHistoryDetailRequest) Reset()         { *m = DescribeHistoryDetailRequest{} }
func (m *DescribeHistoryDetailRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeHistoryDetailRequest) ProtoMessage()    {}
func (*DescribeHistoryDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0669528d4dffbbe2, []int{10}
}

func (m *DescribeHistoryDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeHistoryDetailRequest.Unmarshal(m, b)
}
func (m *DescribeHistoryDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeHistoryDetailRequest.Marshal(b, m, deterministic)
}
func (m *DescribeHistoryDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeHistoryDetailRequest.Merge(m, src)
}
func (m *DescribeHistoryDetailRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeHistoryDetailRequest.Size(m)
}
func (m *DescribeHistoryDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeHistoryDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeHistoryDetailRequest proto.InternalMessageInfo

func (m *DescribeHistoryDetailRequest) GetSearchWord() string {
	if m != nil {
		return m.SearchWord
	}
	return ""
}

func (m *DescribeHistoryDetailRequest) GetSortKey() string {
	if m != nil {
		return m.SortKey
	}
	return ""
}

func (m *DescribeHistoryDetailRequest) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

func (m *DescribeHistoryDetailRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DescribeHistoryDetailRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DescribeHistoryDetailRequest) GetResourceSearch() string {
	if m != nil {
		return m.ResourceSearch
	}
	return ""
}

func (m *DescribeHistoryDetailRequest) GetHistoryId() []string {
	if m != nil {
		return m.HistoryId
	}
	return nil
}

func (m *DescribeHistoryDetailRequest) GetHistoryName() []string {
	if m != nil {
		return m.HistoryName
	}
	return nil
}

func (m *DescribeHistoryDetailRequest) GetAlertName() []string {
	if m != nil {
		return m.AlertName
	}
	return nil
}

func (m *DescribeHistoryDetailRequest) GetRuleName() []string {
	if m != nil {
		return m.RuleName
	}
	return nil
}

func (m *DescribeHistoryDetailRequest) GetEvent() []string {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *DescribeHistoryDetailRequest) GetRuleId() []string {
	if m != nil {
		return m.RuleId
	}
	return nil
}

func (m *DescribeHistoryDetailRequest) GetResourceName() []string {
	if m != nil {
		return m.ResourceName
	}
	return nil
}

func (m *DescribeHistoryDetailRequest) GetRecent() bool {
	if m != nil {
		return m.Recent
	}
	return false
}

type DescribeHistoryDetailResponse struct {
	Total                uint32           `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	HistorydetailSet     []*HistoryDetail `protobuf:"bytes,2,rep,name=historydetail_set,json=historydetailSet,proto3" json:"historydetail_set"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DescribeHistoryDetailResponse) Reset()         { *m = DescribeHistoryDetailResponse{} }
func (m *DescribeHistoryDetailResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeHistoryDetailResponse) ProtoMessage()    {}
func (*DescribeHistoryDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0669528d4dffbbe2, []int{11}
}

func (m *DescribeHistoryDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeHistoryDetailResponse.Unmarshal(m, b)
}
func (m *DescribeHistoryDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeHistoryDetailResponse.Marshal(b, m, deterministic)
}
func (m *DescribeHistoryDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeHistoryDetailResponse.Merge(m, src)
}
func (m *DescribeHistoryDetailResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeHistoryDetailResponse.Size(m)
}
func (m *DescribeHistoryDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeHistoryDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeHistoryDetailResponse proto.InternalMessageInfo

func (m *DescribeHistoryDetailResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *DescribeHistoryDetailResponse) GetHistorydetailSet() []*HistoryDetail {
	if m != nil {
		return m.HistorydetailSet
	}
	return nil
}

func init() {
	proto.RegisterType((*DescribeAlertsWithResourceRequest)(nil), "kubesphere.alert.DescribeAlertsWithResourceRequest")
	proto.RegisterType((*DescribeAlertsWithResourceResponse)(nil), "kubesphere.alert.DescribeAlertsWithResourceResponse")
	proto.RegisterType((*AlertDetail)(nil), "kubesphere.alert.AlertDetail")
	proto.RegisterType((*DescribeAlertDetailsRequest)(nil), "kubesphere.alert.DescribeAlertDetailsRequest")
	proto.RegisterType((*DescribeAlertDetailsResponse)(nil), "kubesphere.alert.DescribeAlertDetailsResponse")
	proto.RegisterType((*ResourceStatus)(nil), "kubesphere.alert.ResourceStatus")
	proto.RegisterType((*AlertStatus)(nil), "kubesphere.alert.AlertStatus")
	proto.RegisterType((*DescribeAlertStatusRequest)(nil), "kubesphere.alert.DescribeAlertStatusRequest")
	proto.RegisterType((*DescribeAlertStatusResponse)(nil), "kubesphere.alert.DescribeAlertStatusResponse")
	proto.RegisterType((*HistoryDetail)(nil), "kubesphere.alert.HistoryDetail")
	proto.RegisterType((*DescribeHistoryDetailRequest)(nil), "kubesphere.alert.DescribeHistoryDetailRequest")
	proto.RegisterType((*DescribeHistoryDetailResponse)(nil), "kubesphere.alert.DescribeHistoryDetailResponse")
}

func init() { proto.RegisterFile("custom.proto", fileDescriptor_0669528d4dffbbe2) }

var fileDescriptor_0669528d4dffbbe2 = []byte{
	// 1717 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xcd, 0x6e, 0x23, 0xc7,
	0x11, 0x06, 0x45, 0xfd, 0x90, 0xc5, 0x5f, 0xb5, 0xb4, 0xd2, 0x98, 0xf6, 0x7a, 0x69, 0xae, 0x63,
	0x0b, 0xc8, 0x8a, 0x74, 0xb4, 0x0b, 0xe4, 0x60, 0x20, 0x80, 0xb2, 0x1b, 0x23, 0x44, 0x36, 0x81,
	0x41, 0x19, 0x30, 0x90, 0xcb, 0x60, 0x34, 0xd3, 0x24, 0x1b, 0x1e, 0xce, 0x4c, 0xba, 0x7b, 0xb4,
	0x16, 0x92, 0x53, 0xf2, 0x06, 0xca, 0x3b, 0xe4, 0x12, 0xe4, 0x90, 0x43, 0x8e, 0x01, 0x12, 0x20,
	0x4f, 0x90, 0x9c, 0x72, 0xcf, 0x25, 0xf7, 0x3c, 0x40, 0xd0, 0x55, 0x3d, 0xe4, 0xcc, 0x90, 0xfa,
	0x59, 0x24, 0x17, 0x03, 0x3e, 0x49, 0xfd, 0x55, 0x75, 0x4f, 0x75, 0xd5, 0x57, 0x5f, 0xcd, 0x10,
	0x9a, 0x7e, 0xaa, 0x74, 0xbc, 0x18, 0x26, 0x32, 0xd6, 0x31, 0xeb, 0x7e, 0x95, 0x5e, 0x72, 0x95,
	0xcc, 0xb9, 0xe4, 0x43, 0x2f, 0xe4, 0x52, 0xf7, 0xde, 0x9b, 0xc5, 0xf1, 0x2c, 0xe4, 0x23, 0x2f,
	0x11, 0x23, 0x2f, 0x8a, 0x62, 0xed, 0x69, 0x11, 0x47, 0x8a, 0xfc, 0x7b, 0xef, 0x5b, 0x2b, 0xae,
	0x2e, 0xd3, 0xe9, 0xe8, 0x8d, 0xf4, 0x92, 0x84, 0xcb, 0xcc, 0xfe, 0x0c, 0xff, 0xf8, 0xa7, 0x33,
	0x1e, 0x9d, 0xaa, 0x37, 0xde, 0x6c, 0xc6, 0xe5, 0x28, 0x4e, 0xf0, 0x84, 0x0d, 0xa7, 0x3d, 0x29,
	0x9f, 0xa6, 0xc5, 0x82, 0x2b, 0xed, 0x2d, 0x12, 0xeb, 0xd0, 0xc0, 0x98, 0x68, 0x31, 0xf8, 0x43,
	0x15, 0x3e, 0x78, 0xc5, 0x95, 0x2f, 0xc5, 0x25, 0x3f, 0x37, 0xb8, 0xfa, 0x52, 0xe8, 0xf9, 0x84,
	0xab, 0x38, 0x95, 0x3e, 0x9f, 0xf0, 0x5f, 0xa4, 0x5c, 0x69, 0xf6, 0x04, 0x1a, 0x8a, 0x7b, 0xd2,
	0x9f, 0xbb, 0x6f, 0x62, 0x19, 0x38, 0x95, 0x7e, 0xe5, 0xa4, 0x3e, 0x01, 0x82, 0xbe, 0x8c, 0x65,
	0xc0, 0xde, 0x81, 0x9a, 0x8a, 0xa5, 0x76, 0xbf, 0xe2, 0xd7, 0xce, 0x16, 0x5a, 0xf7, 0xcc, 0xfa,
	0x27, 0xfc, 0x9a, 0x39, 0xb0, 0x27, 0xf9, 0x15, 0x97, 0x8a, 0x3b, 0xd5, 0x7e, 0xe5, 0xa4, 0x36,
	0xc9, 0x96, 0xec, 0x08, 0x76, 0xe3, 0xe9, 0x54, 0x71, 0xed, 0x6c, 0xf7, 0x2b, 0x27, 0xad, 0x89,
	0x5d, 0xb1, 0x43, 0xd8, 0x09, 0xc5, 0x42, 0x68, 0x67, 0x07, 0x61, 0x5a, 0xb0, 0x8f, 0xa1, 0x23,
	0x6d, 0x58, 0x2e, 0x3d, 0xd9, 0xd9, 0xc5, 0x27, 0xb5, 0x33, 0xf8, 0x02, 0x51, 0x13, 0x0b, 0xde,
	0xd0, 0x15, 0x81, 0xb3, 0xd7, 0xaf, 0x9a, 0x58, 0x70, 0x3d, 0x0e, 0xd8, 0x63, 0x00, 0x32, 0x45,
	0xde, 0x82, 0x3b, 0x35, 0x34, 0xd6, 0x11, 0xf9, 0x99, 0xb7, 0xe0, 0xac, 0x07, 0xb5, 0x40, 0x28,
	0xef, 0x32, 0xe4, 0x81, 0x53, 0xef, 0x57, 0x4f, 0x6a, 0x93, 0xe5, 0x9a, 0x7d, 0x07, 0xda, 0x32,
	0x8d, 0x22, 0x11, 0xcd, 0x5c, 0xa5, 0x3d, 0x9d, 0x2a, 0x07, 0x70, 0x7b, 0xcb, 0xa2, 0x17, 0x08,
	0xb2, 0x77, 0xa1, 0x9e, 0xc4, 0xa1, 0xf0, 0xaf, 0xcd, 0xd3, 0x1b, 0xe8, 0x51, 0x23, 0x60, 0x1c,
	0xb0, 0x3e, 0x34, 0xa5, 0x72, 0xa7, 0x22, 0xd4, 0x5c, 0x1a, 0x7b, 0x13, 0xed, 0x20, 0xd5, 0x67,
	0x08, 0x8d, 0x03, 0x93, 0x68, 0xfe, 0x35, 0xf7, 0x53, 0x1d, 0xa3, 0x43, 0x8b, 0x1c, 0x32, 0x68,
	0x1c, 0x0c, 0x12, 0x18, 0xdc, 0x55, 0x2e, 0x95, 0xc4, 0x91, 0xe2, 0x26, 0x83, 0x3a, 0xd6, 0x5e,
	0x88, 0x95, 0x6a, 0x4d, 0x68, 0xc1, 0x5e, 0x00, 0xdd, 0xd5, 0x35, 0x29, 0xdf, 0xea, 0x57, 0x4f,
	0x1a, 0x67, 0xc7, 0xc3, 0x32, 0x57, 0x87, 0x78, 0xec, 0x84, 0x52, 0x78, 0xc1, 0xf5, 0xe0, 0xdf,
	0xbb, 0xd0, 0x40, 0xec, 0x15, 0xd7, 0x9e, 0x08, 0x0b, 0xe9, 0x25, 0x22, 0xdc, 0x92, 0x5e, 0xe2,
	0xc1, 0x2d, 0xe9, 0x25, 0x2a, 0xac, 0xd2, 0xfb, 0x29, 0x34, 0x7c, 0xc9, 0x3d, 0xcd, 0x5d, 0x43,
	0x57, 0x24, 0x44, 0xe3, 0xac, 0x37, 0x24, 0x2e, 0x0f, 0x33, 0x2e, 0x0f, 0xbf, 0xc8, 0xb8, 0x3c,
	0x01, 0x72, 0x37, 0xc0, 0x86, 0xda, 0xec, 0xe0, 0xb3, 0x4b, 0xb5, 0xf9, 0x00, 0x9a, 0xf6, 0xfe,
	0xe4, 0x44, 0xf4, 0xa1, 0x76, 0xd8, 0x54, 0xbe, 0x3d, 0xb4, 0xaf, 0xca, 0xf7, 0x21, 0xb4, 0x57,
	0xe5, 0xb3, 0x0c, 0x32, 0x1e, 0xcd, 0xac, 0x80, 0x78, 0xcb, 0x8f, 0xa0, 0xb3, 0xf2, 0x4a, 0x3c,
	0xe9, 0x2d, 0x9c, 0xba, 0x8d, 0xc6, 0xba, 0x7d, 0x6e, 0x40, 0x4b, 0x06, 0x7d, 0x9d, 0x70, 0x3a,
	0x0b, 0xa8, 0xa9, 0xa4, 0xfa, 0xe2, 0x3a, 0xe1, 0x78, 0x52, 0x89, 0x0c, 0x0d, 0x72, 0x58, 0x91,
	0xc1, 0x38, 0xd8, 0x68, 0xf1, 0x84, 0x26, 0x39, 0x10, 0x84, 0x27, 0x9c, 0x02, 0xb3, 0x0e, 0x01,
	0x92, 0x06, 0x45, 0xc3, 0x69, 0xa1, 0xdf, 0x3e, 0x59, 0x5e, 0xad, 0x0c, 0xec, 0x29, 0xb4, 0xac,
	0xbb, 0x1f, 0x47, 0x53, 0x31, 0x73, 0xda, 0x74, 0x3f, 0x02, 0x5f, 0x22, 0x66, 0xfa, 0x19, 0x53,
	0x1f, 0x4b, 0xa7, 0x43, 0xe5, 0xb7, 0x4b, 0xf6, 0x09, 0x1c, 0x7a, 0x57, 0x9e, 0x08, 0x4d, 0x45,
	0x4d, 0x8e, 0xa5, 0xa6, 0x62, 0x76, 0xd1, 0x8d, 0x2d, 0x6d, 0x17, 0xc6, 0x84, 0x85, 0x7b, 0x06,
	0x2b, 0xd4, 0xe5, 0x51, 0x40, 0xfe, 0xfb, 0xe8, 0xdf, 0x5d, 0x5a, 0x7e, 0x14, 0x05, 0xe8, 0xdd,
	0x83, 0x5a, 0xe8, 0x45, 0xb3, 0xd4, 0x9b, 0x71, 0x87, 0x51, 0x6d, 0xb2, 0xb5, 0x89, 0x6a, 0xc1,
	0xb5, 0x14, 0xbe, 0x72, 0x0e, 0xa8, 0xe7, 0xed, 0xd2, 0x24, 0x49, 0xa6, 0x21, 0x57, 0xae, 0x1f,
	0xa7, 0x91, 0x76, 0x0e, 0xb1, 0x23, 0x00, 0xa1, 0x97, 0x06, 0x31, 0xc2, 0x92, 0xc4, 0x4a, 0x68,
	0x71, 0xb5, 0x74, 0x7a, 0x84, 0x4e, 0xed, 0x25, 0x4c, 0x8e, 0xcf, 0xe1, 0x68, 0x11, 0x2b, 0xed,
	0x4a, 0xee, 0xf3, 0x48, 0xbb, 0xc4, 0x25, 0x8c, 0xf8, 0x08, 0xa3, 0x39, 0x30, 0xd6, 0x09, 0x1a,
	0xb1, 0x61, 0x30, 0xe8, 0xef, 0x02, 0x8b, 0xa6, 0xae, 0x17, 0x04, 0x92, 0x2b, 0xe5, 0x86, 0x42,
	0x61, 0xe3, 0x1c, 0xe3, 0x86, 0x4e, 0x34, 0x3d, 0x27, 0xc3, 0x6b, 0xa1, 0xf4, 0x38, 0x18, 0xfc,
	0xb5, 0x0a, 0xef, 0x16, 0xda, 0x9b, 0x7a, 0x4e, 0x7d, 0xab, 0xc3, 0xff, 0x57, 0x1d, 0xce, 0x51,
	0x98, 0x24, 0x78, 0x49, 0xe1, 0xb2, 0x42, 0xb7, 0xee, 0x53, 0xe8, 0xf6, 0x9a, 0x42, 0xff, 0x0a,
	0xde, 0xdb, 0x5c, 0xc2, 0x3b, 0xb5, 0xf9, 0x33, 0xe8, 0xe0, 0xfd, 0x03, 0xf4, 0xce, 0x29, 0xf4,
	0xe3, 0x5b, 0x14, 0x9a, 0x8e, 0x9d, 0xb4, 0x73, 0xbb, 0x8c, 0x5a, 0xff, 0x65, 0x0b, 0xda, 0xd9,
	0x38, 0xb0, 0xa9, 0x78, 0x0a, 0xad, 0x65, 0xc1, 0x30, 0xdf, 0x15, 0xab, 0x5a, 0x16, 0xc4, 0x94,
	0x3f, 0x85, 0x96, 0x9f, 0x4a, 0x69, 0x78, 0x1d, 0xf2, 0x2b, 0x1e, 0x5a, 0xf6, 0x34, 0x2d, 0xf8,
	0xda, 0x60, 0x26, 0xf7, 0x59, 0x4b, 0xd8, 0x46, 0xa9, 0xe2, 0x1d, 0x5a, 0x19, 0x4a, 0x7d, 0xf2,
	0x09, 0x1c, 0xfa, 0xe9, 0x22, 0x0d, 0x3d, 0xcd, 0x03, 0x57, 0x99, 0xb6, 0x26, 0x67, 0x62, 0x17,
	0x5b, 0xda, 0x2e, 0x78, 0x14, 0x2c, 0x77, 0x44, 0xfc, 0x6b, 0xd3, 0x59, 0xe8, 0x2e, 0x22, 0xcd,
	0xe5, 0x95, 0x17, 0x5a, 0xe2, 0x31, 0x63, 0x9b, 0xa0, 0x69, 0x6c, 0x2d, 0x46, 0x39, 0x70, 0x87,
	0x01, 0x51, 0x3d, 0xb0, 0x0f, 0x89, 0x88, 0x5d, 0x63, 0xb9, 0xb0, 0x06, 0xdb, 0x84, 0xfb, 0xde,
	0x6c, 0x26, 0xf9, 0x0c, 0x43, 0xc2, 0x94, 0x29, 0x2b, 0xef, 0xdd, 0x95, 0x81, 0x06, 0xea, 0xe0,
	0x6f, 0xdb, 0x76, 0xe0, 0xd9, 0xfc, 0x1d, 0xc3, 0x9e, 0x51, 0x8b, 0xd5, 0xbc, 0xdb, 0x35, 0xcb,
	0x71, 0x60, 0x38, 0x86, 0x86, 0xdc, 0xb4, 0xab, 0x19, 0xe0, 0xde, 0x61, 0xf7, 0x31, 0x74, 0x16,
	0x71, 0x24, 0x0c, 0x85, 0x12, 0x2e, 0x45, 0x1c, 0x28, 0x9b, 0x9b, 0xb6, 0x85, 0x3f, 0x27, 0xd4,
	0x1c, 0xa2, 0x4c, 0x93, 0x0a, 0x7d, 0x6d, 0x47, 0xda, 0x72, 0x6d, 0xa6, 0x99, 0x95, 0x38, 0x1c,
	0x22, 0xd9, 0x34, 0xb3, 0x98, 0x19, 0x22, 0xa6, 0x5e, 0x7e, 0x1c, 0x05, 0xc2, 0x88, 0x3b, 0x39,
	0xd1, 0x9d, 0x5b, 0x4b, 0x14, 0xdd, 0xde, 0x07, 0xd0, 0x73, 0xc9, 0xd5, 0x3c, 0x0e, 0x03, 0x65,
	0x67, 0x5a, 0x0e, 0x61, 0x0c, 0xb6, 0xd3, 0x48, 0x68, 0x3b, 0xc6, 0xf0, 0x7f, 0x93, 0x51, 0xdf,
	0xd0, 0xd9, 0x4f, 0x73, 0x6c, 0x00, 0xbc, 0x44, 0x37, 0x67, 0xa0, 0xf2, 0x3a, 0xb0, 0x27, 0xa2,
	0xb9, 0xb8, 0x14, 0x1a, 0x87, 0x58, 0x6d, 0x92, 0x2d, 0x4d, 0x37, 0x51, 0xc0, 0x85, 0x09, 0x46,
	0x10, 0xa6, 0xf1, 0x07, 0x50, 0xcf, 0x78, 0xaa, 0xb0, 0x1b, 0x1b, 0x67, 0xfd, 0xf5, 0x8e, 0x28,
	0x32, 0x7e, 0xb2, 0xda, 0x52, 0x7e, 0xaf, 0x68, 0xbf, 0xd5, 0x7b, 0xc5, 0xa7, 0xd0, 0x48, 0x93,
	0x60, 0xb9, 0xb9, 0x73, 0xff, 0x66, 0x72, 0x37, 0xc0, 0xe0, 0x9f, 0x55, 0xe8, 0x15, 0x84, 0xc0,
	0x06, 0xf7, 0xad, 0x94, 0x7f, 0x53, 0xa4, 0x3c, 0xdf, 0xf9, 0x1d, 0x34, 0xda, 0xce, 0x1f, 0xfc,
	0xb2, 0x34, 0xa6, 0xb3, 0xd2, 0x3e, 0x48, 0xe2, 0xe9, 0xae, 0x0f, 0x90, 0x78, 0x7b, 0x6a, 0x3b,
	0xb7, 0xcb, 0x48, 0xfc, 0x9f, 0x77, 0xa0, 0xf5, 0x63, 0xa1, 0x74, 0x2c, 0xaf, 0xed, 0x2b, 0xf9,
	0x63, 0x80, 0x39, 0x01, 0x2b, 0x91, 0xaa, 0x5b, 0x64, 0x1c, 0x18, 0xa5, 0xc8, 0xcc, 0x39, 0xa9,
	0x6a, 0x58, 0x0c, 0xcb, 0x94, 0xbb, 0x69, 0xf5, 0x76, 0x8d, 0xdb, 0x2e, 0x69, 0xdc, 0x21, 0xec,
	0xf0, 0x2b, 0x1e, 0x69, 0xab, 0x4d, 0xb4, 0x30, 0xac, 0x8a, 0x62, 0x2d, 0xa6, 0xc2, 0xc7, 0xef,
	0x52, 0x73, 0xa6, 0x65, 0x55, 0x1e, 0x1e, 0x07, 0x6c, 0x04, 0x07, 0x05, 0x47, 0x4b, 0x02, 0xd2,
	0x28, 0x96, 0x37, 0x59, 0x26, 0xe4, 0xe5, 0xb0, 0x56, 0x92, 0xc3, 0xf2, 0xeb, 0x74, 0x7d, 0xed,
	0x75, 0x7a, 0xfd, 0xf5, 0x1d, 0x36, 0xbc, 0xbe, 0x97, 0x14, 0xa9, 0xb1, 0xa6, 0x48, 0xeb, 0xa2,
	0xda, 0xbc, 0x5f, 0x54, 0x5b, 0xb7, 0x8a, 0x6a, 0x3b, 0x27, 0xaa, 0xc5, 0x5e, 0xea, 0x94, 0xbf,
	0x9f, 0x36, 0x7c, 0x59, 0x74, 0x37, 0x7d, 0x59, 0xac, 0x0d, 0xfc, 0xfd, 0x0d, 0x03, 0xbf, 0x24,
	0x8c, 0xec, 0x7f, 0x11, 0xc6, 0x83, 0xb7, 0x12, 0xc6, 0x3f, 0x55, 0x57, 0x6f, 0x48, 0x05, 0x1e,
	0x7f, 0x23, 0xa5, 0xb1, 0xd8, 0x7b, 0x24, 0x8e, 0x77, 0xf4, 0x1e, 0x09, 0x64, 0xa1, 0xf7, 0x8a,
	0x55, 0xaf, 0x97, 0x15, 0xb4, 0xd0, 0x81, 0x24, 0x90, 0x1b, 0x3a, 0x90, 0x74, 0xd1, 0x76, 0x60,
	0xae, 0x9b, 0x9b, 0x79, 0xdd, 0x5a, 0x67, 0x06, 0x89, 0x62, 0x91, 0x19, 0x47, 0xb0, 0x4b, 0x5f,
	0x38, 0xc8, 0xcd, 0xda, 0xc4, 0xae, 0x06, 0xbf, 0xa9, 0xc0, 0xe3, 0x5b, 0xea, 0x76, 0xa7, 0xee,
	0xbd, 0x86, 0x7d, 0x7b, 0xdd, 0xb5, 0x97, 0xdb, 0x27, 0xeb, 0xca, 0x57, 0x3c, 0xb9, 0x5b, 0xd8,
	0x79, 0xc1, 0xf5, 0xd9, 0x7f, 0x76, 0x80, 0xa1, 0x3a, 0xfe, 0xd4, 0x8b, 0xbc, 0x19, 0x97, 0x2f,
	0xf1, 0x97, 0x37, 0xf6, 0xf7, 0x4a, 0x69, 0xda, 0x16, 0x7e, 0x18, 0x61, 0xcf, 0xd7, 0x1f, 0x74,
	0xef, 0xaf, 0x5e, 0xbd, 0x17, 0x6f, 0xb7, 0x89, 0x92, 0x30, 0x18, 0xdf, 0x9c, 0x7f, 0xc4, 0x3e,
	0x0c, 0xac, 0x63, 0x9f, 0xc4, 0xbb, 0xff, 0x46, 0xe8, 0x79, 0x3f, 0x4b, 0x73, 0x9f, 0x18, 0xf5,
	0xeb, 0x7f, 0xfc, 0xeb, 0xb7, 0x5b, 0x3d, 0xe6, 0x8c, 0xae, 0xbe, 0x37, 0x22, 0x37, 0xd7, 0xb8,
	0xb9, 0x99, 0x1b, 0xfb, 0x7d, 0x05, 0x0e, 0x37, 0x7d, 0x4b, 0xb0, 0xd3, 0x7b, 0x22, 0x2b, 0x7e,
	0x36, 0xf6, 0x86, 0x0f, 0x75, 0xb7, 0x57, 0x78, 0x71, 0x73, 0xee, 0xb0, 0xa3, 0xe2, 0x15, 0xfa,
	0x54, 0x02, 0x85, 0x41, 0x1f, 0xb0, 0xfd, 0x65, 0xd0, 0xae, 0x35, 0xb0, 0xdf, 0x55, 0xe0, 0x60,
	0xc3, 0x54, 0x64, 0xcf, 0xee, 0x79, 0x7a, 0xe1, 0xbd, 0xa8, 0x77, 0xfa, 0x40, 0x6f, 0x1b, 0xea,
	0xd9, 0xcd, 0xf9, 0x31, 0x7b, 0x54, 0x0a, 0x95, 0x06, 0x09, 0x46, 0xca, 0x58, 0x77, 0x15, 0x29,
	0xe1, 0xec, 0x8f, 0x15, 0x78, 0xb4, 0x91, 0xc8, 0xec, 0x8e, 0x44, 0x6d, 0x52, 0xaa, 0xde, 0xe8,
	0xc1, 0xfe, 0x36, 0xdc, 0xef, 0xdf, 0x9c, 0xbf, 0xc3, 0x8e, 0x97, 0xe1, 0x5a, 0x76, 0xdb, 0xdc,
	0x62, 0xc0, 0x8f, 0xd8, 0x81, 0x09, 0x38, 0x13, 0x0d, 0x9b, 0xdc, 0x1f, 0x6e, 0xff, 0x7c, 0x2b,
	0xb9, 0xbc, 0xdc, 0x45, 0x69, 0x7d, 0xfe, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xc1, 0x70,
	0xc4, 0x70, 0x16, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AlertManagerCustomClient is the client API for AlertManagerCustom service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AlertManagerCustomClient interface {
	//0.Alert
	//********************************************************************************************************
	DescribeAlertsWithResource(ctx context.Context, in *DescribeAlertsWithResourceRequest, opts ...grpc.CallOption) (*DescribeAlertsWithResourceResponse, error)
	DescribeAlertDetails(ctx context.Context, in *DescribeAlertDetailsRequest, opts ...grpc.CallOption) (*DescribeAlertDetailsResponse, error)
	DescribeAlertStatus(ctx context.Context, in *DescribeAlertStatusRequest, opts ...grpc.CallOption) (*DescribeAlertStatusResponse, error)
	//1.History
	//********************************************************************************************************
	DescribeHistoryDetail(ctx context.Context, in *DescribeHistoryDetailRequest, opts ...grpc.CallOption) (*DescribeHistoryDetailResponse, error)
}

type alertManagerCustomClient struct {
	cc *grpc.ClientConn
}

func NewAlertManagerCustomClient(cc *grpc.ClientConn) AlertManagerCustomClient {
	return &alertManagerCustomClient{cc}
}

func (c *alertManagerCustomClient) DescribeAlertsWithResource(ctx context.Context, in *DescribeAlertsWithResourceRequest, opts ...grpc.CallOption) (*DescribeAlertsWithResourceResponse, error) {
	out := new(DescribeAlertsWithResourceResponse)
	err := c.cc.Invoke(ctx, "/kubesphere.alert.AlertManagerCustom/DescribeAlertsWithResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagerCustomClient) DescribeAlertDetails(ctx context.Context, in *DescribeAlertDetailsRequest, opts ...grpc.CallOption) (*DescribeAlertDetailsResponse, error) {
	out := new(DescribeAlertDetailsResponse)
	err := c.cc.Invoke(ctx, "/kubesphere.alert.AlertManagerCustom/DescribeAlertDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagerCustomClient) DescribeAlertStatus(ctx context.Context, in *DescribeAlertStatusRequest, opts ...grpc.CallOption) (*DescribeAlertStatusResponse, error) {
	out := new(DescribeAlertStatusResponse)
	err := c.cc.Invoke(ctx, "/kubesphere.alert.AlertManagerCustom/DescribeAlertStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagerCustomClient) DescribeHistoryDetail(ctx context.Context, in *DescribeHistoryDetailRequest, opts ...grpc.CallOption) (*DescribeHistoryDetailResponse, error) {
	out := new(DescribeHistoryDetailResponse)
	err := c.cc.Invoke(ctx, "/kubesphere.alert.AlertManagerCustom/DescribeHistoryDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertManagerCustomServer is the server API for AlertManagerCustom service.
type AlertManagerCustomServer interface {
	//0.Alert
	//********************************************************************************************************
	DescribeAlertsWithResource(context.Context, *DescribeAlertsWithResourceRequest) (*DescribeAlertsWithResourceResponse, error)
	DescribeAlertDetails(context.Context, *DescribeAlertDetailsRequest) (*DescribeAlertDetailsResponse, error)
	DescribeAlertStatus(context.Context, *DescribeAlertStatusRequest) (*DescribeAlertStatusResponse, error)
	//1.History
	//********************************************************************************************************
	DescribeHistoryDetail(context.Context, *DescribeHistoryDetailRequest) (*DescribeHistoryDetailResponse, error)
}

// UnimplementedAlertManagerCustomServer can be embedded to have forward compatible implementations.
type UnimplementedAlertManagerCustomServer struct {
}

func (*UnimplementedAlertManagerCustomServer) DescribeAlertsWithResource(ctx context.Context, req *DescribeAlertsWithResourceRequest) (*DescribeAlertsWithResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeAlertsWithResource not implemented")
}
func (*UnimplementedAlertManagerCustomServer) DescribeAlertDetails(ctx context.Context, req *DescribeAlertDetailsRequest) (*DescribeAlertDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeAlertDetails not implemented")
}
func (*UnimplementedAlertManagerCustomServer) DescribeAlertStatus(ctx context.Context, req *DescribeAlertStatusRequest) (*DescribeAlertStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeAlertStatus not implemented")
}
func (*UnimplementedAlertManagerCustomServer) DescribeHistoryDetail(ctx context.Context, req *DescribeHistoryDetailRequest) (*DescribeHistoryDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeHistoryDetail not implemented")
}

func RegisterAlertManagerCustomServer(s *grpc.Server, srv AlertManagerCustomServer) {
	s.RegisterService(&_AlertManagerCustom_serviceDesc, srv)
}

func _AlertManagerCustom_DescribeAlertsWithResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeAlertsWithResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagerCustomServer).DescribeAlertsWithResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubesphere.alert.AlertManagerCustom/DescribeAlertsWithResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagerCustomServer).DescribeAlertsWithResource(ctx, req.(*DescribeAlertsWithResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagerCustom_DescribeAlertDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeAlertDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagerCustomServer).DescribeAlertDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubesphere.alert.AlertManagerCustom/DescribeAlertDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagerCustomServer).DescribeAlertDetails(ctx, req.(*DescribeAlertDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagerCustom_DescribeAlertStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeAlertStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagerCustomServer).DescribeAlertStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubesphere.alert.AlertManagerCustom/DescribeAlertStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagerCustomServer).DescribeAlertStatus(ctx, req.(*DescribeAlertStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagerCustom_DescribeHistoryDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeHistoryDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagerCustomServer).DescribeHistoryDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubesphere.alert.AlertManagerCustom/DescribeHistoryDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagerCustomServer).DescribeHistoryDetail(ctx, req.(*DescribeHistoryDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AlertManagerCustom_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubesphere.alert.AlertManagerCustom",
	HandlerType: (*AlertManagerCustomServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribeAlertsWithResource",
			Handler:    _AlertManagerCustom_DescribeAlertsWithResource_Handler,
		},
		{
			MethodName: "DescribeAlertDetails",
			Handler:    _AlertManagerCustom_DescribeAlertDetails_Handler,
		},
		{
			MethodName: "DescribeAlertStatus",
			Handler:    _AlertManagerCustom_DescribeAlertStatus_Handler,
		},
		{
			MethodName: "DescribeHistoryDetail",
			Handler:    _AlertManagerCustom_DescribeHistoryDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "custom.proto",
}
